apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sap-bizai-pulse
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - sap-bizai-pulse.c-5a930ed.kyma.ondemand.com
  service:
    name: sap-bizai-pulse
    port: 80
  rules:
    - path: /*
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      noAuth: true
